nixify: update envrc to improve the caching performance

diff --git a/pkgs/nixify/envrc b/pkgs/nixify/envrc
--- a/pkgs/nixify/envrc
+++ b/pkgs/nixify/envrc
@@ -1,41 +1,37 @@
-# Usage: use_nix [...]
+# Load environment variables from `nix-shell` and export it out.
 #
-# Load environment variables from `nix-shell`.
-# If you have a `default.nix` or `shell.nix` one of these will be used and
-# the derived environment will be stored at ./.direnv/env-<hash>
-# and symlink to it will be created at ./.direnv/default.
-# Dependencies are added to the GC roots, such that the environment remains persistent.
+# Usage: use_nix -s <nix-expression> [-w path] [-w path] ...
+#   -s nix-expression: The nix expression to use for building the shell environment.
+#   -w path: watch a file for changes. It can be specified multiple times. The
+#      shell specified with -s is automatically watched.
 #
-# The resulting environment is cached for better performance.
+# Example: use_nix -s shell.nix -w .nixpkgs-version.json
 #
-# To trigger switch to a different environment:
-# `rm -f .direnv/default`
+# The dependencies pulled by nix-shell are added to Nix's garbage collector
+# roots, such that the environment remains persistent.
 #
-# To derive a new environment:
-# `rm -rf .direnv/env-$(md5sum {shell,default}.nix 2> /dev/null | cut -c -32)`
+# Nix-shell is invoked only once per environment, and the output is cached for
+# better performance. If any of the watched files change, then the environment
+# is rebuilt.
 #
-# To remove cache:
-# `rm -f .direnv/dump-*`
+# To remove old environments, and allow the GC to collect their dependencies:
+# rm -f .direnv
 #
-# To remove all environments:
-# `rm -rf .direnv/env-*`
-#
-# To remove only old environments:
-# `find .direnv -name 'env-*' -and -not -name `readlink .direnv/default` -exec rm -rf {} +`
-#
-
-set -eo pipefail
-
 use_nix() {
-	# define all local variables
-	local shell f env_hash dir default wd drv dump path_backup
-	local files_to_watch=()
-	
-	declare opt
-        declare OPTARG
-        declare OPTIND
+	if ! validate_version; then
+		echo "This .envrc requires direnv version 2.18.2 or above."
+		exit 1
+	fi
 
-	while getopts ":s:w:" opt; do
+	# define all local variables
+	local shell
+	local files_to_watch=()
+
+	# XXX: These are required so getopts in one function call does not affect the
+	# same call in another function.
+	local opt OPTARG OPTIND
+
+	while getopts ":n:s:w:" opt; do
 		case "${opt}" in
 			s)
 				shell="${OPTARG}"
@@ -45,57 +41,58 @@ use_nix() {
 				files_to_watch=("${files_to_watch[@]}" "${OPTARG}")
 				;;
 			:)
-				>&2 echo "Invalid option: $OPTARG requires an argument"
+				fail "Invalid option: $OPTARG requires an argument"
 				;;
 			\?)
-				>&2 echo "Invalid option: $OPTARG"
-				exit 1
+				fail "Invalid option: $OPTARG"
 				;;
 		esac
 	done
 	shift $((OPTIND -1))
 
 	if [[ -z "${shell}" ]]; then
-		>&2 echo "ERR: no shell was given"
-		exit 1
+		fail "ERR: no shell was given"
 	fi
 
+	local f
 	for f in "${files_to_watch[@]}"; do
 		if ! [[ -f "${f}" ]]; then
-			>&2 echo "cannot watch file ${f} because it does not exist"
-			exit 1
+			fail "cannot watch file ${f} because it does not exist"
 		fi
 	done
 
 	# compute the hash of all the files that makes up the development environment
-	env_hash="$(hashContents "${files_to_watch[@]}")"
+	local env_hash="$(hash_contents "${files_to_watch[@]}")"
 
-	dir="$(direnv_layout_dir)"
-	default="${dir}/default"
-	if [[ ! -L "${default}" ]] || [[ ! -d $(readlink "${default}") ]]; then
-		wd="${dir}/env-${env_hash}"
+	# define the paths
+	local dir="$(direnv_layout_dir)"
+	local wd="${dir}/wd-${env_hash}"
+	local drv="${wd}/env.drv"
+	local dump="${wd}/dump.env"
+
+	# Generate the environment if we do not have one generated already.
+	if [[ ! -f "${drv}" ]]; then
 		mkdir -p "${wd}"
 
-		drv="${wd}/env.drv"
-		if [[ ! -f "${drv}" ]]; then
-			log_status "use nix: deriving new environment"
-			IN_NIX_SHELL=1 nix-instantiate --add-root "${drv}" --indirect "${shell}" > /dev/null
-			nix-store -r $(nix-store --query --references "${drv}") --add-root "${wd}/dep" --indirect > /dev/null
+		# XXX: Once https://github.com/cachix/cachix/issues/189 is resolved,
+		# replace the hardcoded `--option binary-caches` and `--option
+		# trusted-public-keys` with whatever API they deliver.
+
+		log_status "use nix: deriving new environment"
+		IN_NIX_SHELL=1 nix-instantiate --add-root "${drv}" --indirect "${shell}" > /dev/null
+		nix-store -r $(nix-store --query --references "${drv}") --add-root "${wd}/dep" --indirect > /dev/null
+		if [[ "${?}" -ne 0 ]] || [[ ! -f "${drv}" ]]; then
+			rm -rf "${wd}"
+			fail "use nix: was not able to derive the new environment. Please run 'direnv reload' to try again."
 		fi
 
-		rm -f "${default}"
-		ln -s $(basename "${wd}") "${default}"
-	fi
-
-	drv=$(readlink "${default}/env.drv")
-	dump="${dir}/dump-$(hashFile ".envrc")-$(hashFile ${drv})"
-
-	if [[ ! -f "${dump}" ]] || [[ "${XDG_CONFIG_DIR}/direnv/direnvrc" -nt "${dump}" ]]; then
 		log_status "use nix: updating cache"
-
-		old=$(find "${dir}" -name 'dump-*')
-		nix-shell --pure "${drv}" --show-trace --run "$(join_args "$direnv" dump bash)" > "${dump}"
-		rm -f ${old}
+		nix-shell --pure "${drv}" \
+			--show-trace --run "$(join_args "$direnv" dump bash)" > "${dump}"
+		if [[ "${?}" -ne 0 ]] || [[ ! -f "${dump}" ]] || ! grep -q IN_NIX_SHELL "${dump}"; then
+			rm -rf "${wd}"
+			fail "use nix: was not able to update the cache of the environment. Please run 'direnv reload' to try again."
+		fi
 	fi
 
 	# evaluate the dump created by nix-shell earlier, but have to merge the PATH
@@ -103,29 +100,17 @@ use_nix() {
 	# NOTE: we eval the dump here as opposed to direnv_load it because we don't
 	# want to persist environment variables coming from the shell at the time of
 	# the dump. See https://github.com/direnv/direnv/issues/405 for context.
-	path_backup="${PATH}"
+	local path_backup="${PATH}"
 	eval $(cat "${dump}")
 	export PATH="${PATH}:${path_backup}"
 
+	# cleanup the environment of variables that are not requried, or are causing issues.
+	unset shellHook  # when shellHook is present, then any nix-shell'd script will execute it!
+
+	# watch all the files we were asked to watch for the environment
 	for f in "${files_to_watch[@]}"; do
 		watch_file "${f}"
 	done
-}
-
-hashContents() {
-	if has md5sum; then
-		cat "${@}" | md5sum | cut -c -32
-	elif has md5; then
-		cat "${@}" | md5 -q
-	fi
-}
-
-hashFile() {
-	if has md5sum; then
-		md5sum "${@}" | cut -c -32
-	elif has md5; then
-		md5 -q "${@}"
-	fi
 }
 
 fail() {
@@ -133,7 +118,23 @@ fail() {
 	exit 1
 }
 
-validateVersion() {
+hash_contents() {
+	if has md5sum; then
+		cat "${@}" | md5sum | cut -c -32
+	elif has md5; then
+		cat "${@}" | md5 -q
+	fi
+}
+
+hash_file() {
+	if has md5sum; then
+		md5sum "${@}" | cut -c -32
+	elif has md5; then
+		md5 -q "${@}"
+	fi
+}
+
+validate_version() {
 	local version="$("${direnv}" version)"
 	local major="$(echo "${version}" | cut -d. -f1)"
 	local minor="$(echo "${version}" | cut -d. -f2)"
@@ -144,10 +145,5 @@ validateVersion() {
 	if [[ "${major}" -eq 2 ]] && [[ "${minor}" -eq 18 ]] && [[ "${patch}" -ge 2 ]]; then return 0; fi
 	return 1
 }
-
-if ! validateVersion; then
-	echo "This .envrc requires direnv version 2.18.2 or above."
-	exit 1
-fi
 
 use_nix -s shell.nix -w .nixpkgs-version.json
